# Generated by Django 4.1.7 on 2023-04-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_interactedwith_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactedwith',
            name='faved',
            field=models.BooleanField(default=False),
        ),
    ]
