# Generated by Django 4.1.7 on 2023-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_interactedwith_faved'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactedwith',
            name='shoppinglist',
            field=models.BooleanField(default=False),
        ),
    ]
