# Generated by Django 4.1.7 on 2023-04-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_comment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='units',
            field=models.CharField(choices=[('None', 'None'), ('cup', 'cup(s)'), ('tsp', 'teaspoon(s)'), ('tbsp', 'tablespoon(s)'), ('pound', 'pound(s)')], default='None', max_length=5),
        ),
    ]
